### ISSUE TITLE
Table header border client style is not reset

### ISSUE THREAD

**Issue by DaveSenn** [twbs/bootstrap-sass#1011]
Bootstrap does not reset the borders of table headers and table cells.
Which results in inconsistent tables across different browsers.
Example: http://www.bootply.com/q1jvO9muGx  (First table contains the "fix")

Is it correct that the client style does not get reset or is it a bug?
If it’s a bug, adding the following style to the _normalize.scss file would fix the problem:
```scss
// Line 421
td,
th {
    padding: 0;
    // New
    border: none;
}
```
