### ISSUE TITLE
Is SASS-style "@extend" weird?

### ISSUE THREAD

**Issue by monoblaine** [twbs/bootstrap-sass#1028]
I'm trying to migrate my projects from Less to Sass and occasionally comparing preprocessor output to make sure I'm not doing anything wrong (totally new to sass world).

I had the initial impression that the `@extend` of Sass and the `:extend` of Less were doing pretty much the same thing. However `@extend` seems to be doing its job more "aggressively".

There are 8 places where `@extend` is used in Bootstrap's Sass port, and one of them is in `_button-groups.scss`:

```scss
.btn-group-lg > .btn { @extend .btn-lg; } // line 98
```
Less side: (`button-groups.less`)

```less
.btn-group-lg > .btn { &:extend(.btn-lg); } // line 98
```

When compiled, Sass inserts (frantically, imho) `.btn-group-lg > .btn` and its variations for every single matching `.btn-lg` selector. For instance, one of the rules produced by Less is:

```css
.btn-group > .btn-lg + .dropdown-toggle {
    padding-right: 12px;
    padding-left: 12px;
}
```
Sass, however creates this:

```css
.btn-group > .btn-lg + .dropdown-toggle,
.btn-group-lg.btn-group > .btn + .dropdown-toggle {
    padding-right: 12px;
    padding-left: 12px;
}
```
All the components that use `@extend` (navs, input-groups, button-groups) similarly produces extra rules. (Rules that are not present in Less output) Is this the normal behavior? Is it because I use node-sass or somehing else?

I've created an example app for the comparison:
https://github.com/monoblaine/bootstrap-3-sass-extend-oddity

**Comment by WizardCM** [comment]
I've noticed the same.

Before (my original code):

```css
	button:not(.btn-lg) {
		text-transform: uppercase;
	}
```

After (once compiled):

```css
	button:not(.btn-lg):not(.btn-group-lg > .btn) {
		text-transform: uppercase;
	}
```
Which is entirely invalid in CSS, causing a parsing error. The browser skips it.
