### ISSUE TITLE
CSS error in _forms.scss

### ISSUE THREAD

**Issue by tschechniker** [twbs/bootstrap-sass#1128]
Hi,

in Line 55 of _forms.scss (https://github.com/twbs/bootstrap-sass/blob/3.3-stable/assets/stylesheets/bootstrap/_forms.scss#L55):

```css
// Position radios and checkboxes better
input[type="radio"],
input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9; // IE8-9
  line-height: normal;
}
```

The \9 seems to be an error because it renders to  the following css:
```css
input[type="radio"], input[type="checkbox"] {
  margin: 4px 0 0;
  margin-top: 1px \9;
  line-height: normal; }
```

This is an invalid css. The \9 should be removed.

Best regards

Tobias
