### ISSUE TITLE
Responsive menu not working 

### ISSUE THREAD

**Issue by murtaza52** [twbs/bootstrap-sass#175]
Hi,

I have created a sample app using bootstrap-sass. Then changed the application.css to use the sass bootstrap.  Below is my new application.css.scss file - 

``` scss
@import "bootstrap";
body { padding-top: 60px; }
@import "bootstrap-responsive";
@import "scaffolds";
@import "posts";
```

Then when I navigate to my locahost:3000/posts url, I can see the form page with all the proper styles. However when I resize the browser window, I do see a button on the top right for the navigation links, however clicking on the button doesnt do anything. 

Please navigate to localhost:3000/posts to see the behavior.

I have uploaded the sample project on github - https://github.com/murtaza52/rails-base

I tried out the same thing with the less version of bootstrap and the responsive behavior works fine there - https://github.com/seyhunak/twitter-bootstrap-rails/

Thanks,
Murtaza
