### ISSUE TITLE
Stacked progress bars are stacked vertically

### ISSUE THREAD

**Issue by gdlx** [twbs/bootstrap-sass#186]
There are differences between official Bootstrap and booststrap-sass for progress bars :

https://github.com/thomas-mcdonald/bootstrap-sass/blob/master/vendor/assets/stylesheets/bootstrap/_progress-bars.scss#L54

``` css
.progress .bar {
  width: 0%;
  height: 18px;
  color: $white;
  font-size: 12px;
  text-align: center;
  text-shadow: 0 -1px 0 rgba(0,0,0,.25);
  @include gradient-vertical(#149bdf, #0480be);
  @include box-shadow(inset 0 -1px 0 rgba(0,0,0,.15));
  @include box-sizing(border-box);
  @include transition(width .6s ease);
}
```

https://github.com/twitter/bootstrap/blob/master/less/progress-bars.less#L55

``` css
.progress .bar {
  width: 0%;
  height: 100%;
  color: @white;
  float: left;
  font-size: 12px;
  text-align: center;
  text-shadow: 0 -1px 0 rgba(0,0,0,.25);
  #gradient > .vertical(#149bdf, #0480be);
  .box-shadow(inset 0 -1px 0 rgba(0,0,0,.15));
  .box-sizing(border-box);
  .transition(width .6s ease);
}
```

Differences are :
- `height` (not very problematic)
- `float: left` missing => This miss makes stacked progress bars unusable since they are stacked vertically instead of horizontally.
