### ISSUE TITLE
Form Inputs focus shadow cannot be altered by variable

### ISSUE THREAD

**Issue by Zaraka** [twbs/bootstrap-sass#280]
in _forms.css.scss#125

``` scss
  // Focus state
  &:focus {
    border-color: rgba(82,168,236,.8);
    outline: 0;
    outline: thin dotted \9; /* IE6-9 */
    @include box-shadow(inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px rgba(82,168,236,.6));
  }
```

could be changed to

``` scss
  &:focus {
    border-color: $formBorderColorFocus;
    outline: 0;
    outline: thin dotted \9; /* IE6-9 */
    @include box-shadow(inset 0 1px 1px rgba(0,0,0,.075), 0 0 8px $formBorderColorFocus);
  }
```

or something like that, you get the idea
