### ISSUE TITLE
container when used under nav recieves "width: auto;"

### ISSUE THREAD

**Issue by wiredin** [twbs/bootstrap-sass#319]
I've got a div using the container class as follows:

``` html
<header class="navbar">
    <div class="nav-inner">
         <div class="container">

         </div>
     </div>
</header>
```

container gets styled incorrectly:

``` css
.navbar .container {
width: auto;
}
```

Pretty sure it should be the following:

``` css
media="all"
custom.css:6971@media (min-width: 1200px)
.container, .navbar-static-top .container, .navbar-fixed-top .container, .navbar-fixed-bottom .container {
width: 1170px;
}
```
