### ISSUE TITLE
Sass-helpers path is wrong

### ISSUE THREAD

**Issue by brandonhilkert** [twbs/bootstrap-sass#539]
Rails 4.0.3
Ruby 2.1.0
bootstrap-sass (3.1.1.0)
    sass-rails (4.0.1)
      railties (>= 4.0.0, < 5.0)
      sass (>= 3.1.10)
      sprockets-rails (~> 2.0.0)

If i have `app/assets/stylesheets/application.css.scss` with:

``` css
body {
  background-url: image-url('bg.jpg')
}
```

The result is `/images/bg.jpg`.

If I use https://github.com/anjlab/bootstrap-rails (which I used to, but the README suggests using this gem), i get the right path:  `/assets/bg.jpg`
