### ISSUE TITLE
.checkbox styles do not match original bootstrap

### ISSUE THREAD

**Issue by jrochkind** [twbs/bootstrap-sass#634]
Original `less` bootstrap 3.1.1:

https://github.com/twbs/bootstrap/blob/v3.1.1/less/forms.less#L191-L202

``` less
.radio,
.checkbox {
  display: block;
  min-height: @line-height-computed; // clear the floating input if there is no label text
  margin-top: 10px;
  margin-bottom: 10px;
  padding-left: 20px;
  label {
    display: inline;
    font-weight: normal;
    cursor: pointer;
  }
}
```

bootstrap sass 3.1.1+2
https://github.com/twbs/bootstrap-sass/blob/v3.1.1%2B2/vendor/assets/stylesheets/bootstrap/_forms.scss#L207-L220

``` scss
.radio,
.checkbox {
  display: block;
  min-height: $line-height-computed; // clear the floating input if there is no label text
  margin-top: 10px;
  margin-bottom: 10px;

  label {
    padding-left: 20px;
    margin-bottom: 0;
    font-weight: normal;
    cursor: pointer;
  }
}
```

Please note that in original bootstrap, there is a `padding-left: 20px` applying to `.radio, .checkbox`.  But in bootstrap-sass, that padding-left has been moved down to apply only to the inner `label`, to apply to a label inside a `.radio` or `.checkbox`, instead of to any `.radio, .checkbox`.  And there are other differences as well in the `label` definition. 

I am getting improper display of bootstrap checkboxes in my app, I tracked it down to this. 

Now, I notice that bootstrap-sass 3.1.1 _does_ seem to match.  I can't figure out what the `+2` means. I would have thought it meant bugfixes relevant only to `bootstrap-sass` -- but in this case, it seems to be changes that aren't bugfixes, and may be the opposite. 

The current 3.1.1+1 and 3.1.1+2 (I am actually using rubygem 3.1.1.1) is not working right for me, checkboxes are in some cases displaying wrong, and I have tracked it down to this discrepency. 

Please advise! Thanks!
