### ISSUE TITLE
bootstrap-sass 3.2 breaks glyphicons asset pipeline from 3.1

### ISSUE THREAD

**Issue by rebelwarrior** [twbs/bootstrap-sass#653]
Ok here is the issue:
The Rails 4.1.2 app is looking in:
`/assets/bootstrap/glyphicons-halflings-regular.woff`
yet asset in production is called:
`/assets/bootstrap/glyphicons-halflings-regular-{hash}.woff`
**The request is missing the ~hash~ part.**

Put the fonts in my assets/fonts directory && overwrote the application.css.scss (actually custom.css.scss) file to this:

``` scss
@import "bootstrap-sprockets";
@import "bootstrap";

/* Import the fonts */
@font-face {
  font-family: 'Glyphicons Halflings';
  src: font-url('glyphicons-halflings-regular.eot');
  src: font-url('glyphicons-halflings-regular.eot?#iefix') format('embedded-opentype'),
       font-url('glyphicons-halflings-regular.woff') format('woff'),
       font-url('glyphicons-halflings-regular.ttf') format('truetype'),
       font-url('glyphicons-halflings-regular.svg#glyphicons_halflingsregular') format('svg');
}
```

Now it looks for them in: 
`/assets/glyphicons-halflings-regular.woff`
but still no hash is being appended to the name. 

Application.rb has this line:

``` ruby
  # For Bootstrap Sass
    config.assets.precompile = config.assets.precompile + %w(*.png *.jpg *.jpeg *.gif *.woff *.ttf *.svg *.eot)
```

This problem occured with the upgrade from bootstrap-sass from 3.1.1.1 to 3.2.0.0
