### ISSUE TITLE
Add $grid-columns argument to grid mixins

### ISSUE THREAD

**Issue by silvenon** [twbs/bootstrap-sass#663]
And make it default to `$grid-columns`. For example:

``` scss
// Generate the extra small columns
@mixin make-xs-column($columns, $gutter: $grid-gutter-width, $grid-columns: $grid-columns) {
  position: relative;
  float: left;
  width: percentage(($columns / $grid-columns));
  min-height: 1px;
  padding-left:  ($gutter / 2);
  padding-right: ($gutter / 2);
}
```

Don't know how Sass reacts the argument being named the same as global, though.

I would love to see this feature, though I'm not sure if I'm overseeing something obvious.
