### ISSUE TITLE
Glyphicons Showing Rectangle in "Compass without Rails" Install

### ISSUE THREAD

**Issue by fxruizx** [twbs/bootstrap-sass#667]
I found similar Bootstrap Sass 3.2 glyphicon issues, but these pertained to the Ruby or Rails version installs. Here is the issue I am having with the Compass only install, after running these lines

$ gem install bootstrap-sass
$ compass create MyProject -r bootstrap-sass --using bootstrap

Within sass/_bootstrap-variables.scss I updated the $icon-font-path variable (line 78) testing both relative paths and absolute paths to my glyphicon font files (located in /css/fonts/bootstrap/). Neither relative or absolute, worked.

After looking at the processed style.css file i noticed that @font-face was being structured like this:

``` css
@font-face {
  font-family: 'Glyphicons Halflings';
  src: url(url(/css/fonts/bootstrap/glyphicons-halflings-regular.eot));
  src: url(url(/css/fonts/bootstrap/glyphicons-halflings-regular.eot?#iefix)) format("embedded-opentype"), url(url(/css/fonts/bootstrap/glyphicons-halflings-regular.woff)) format("woff"), url(url(/css/fonts/bootstrap/glyphicons-halflings-regular.ttf)) format("truetype"), url(url(/css/fonts/bootstrap/glyphicons-halflings-regular.svg#glyphicons_halflingsregular)) format("svg");
}
```

Notice the extra "url(" in each src: call. I have no idea what is causing this as i am not including it as part of the $icon-font-path. I am using grunt-contrib-compass but have not changed my Gruntfile.js, and glyphicons worked in v3.1 of bootstrap-sass.

For further reference:
**My config.rb file**

``` ruby
require 'bootstrap-sass'
http_path = "/"
css_dir = "css"
sass_dir = "sass"
images_dir = "images"
javascripts_dir = "javascripts"
```

**My styles.scss file**

``` sass
@import "bootstrap-compass";
@import "bootstrap-variables";
@import "bootstrap";
```

And just because I was trying several things, i added @import "bootstrap-sprockets" and when doing this, instead of an extra "url(" being added, "font-path(" is added e.g.: src: url(font-path(/css/fonts/bootstrap/glyphicons-halflings-regular.eot));

I can fix this issue temporarily by editing the styles.css file to remove the extra "url(" from each @font-face src call, but when Grunt runs again, this is added back in.

Please let me know if I am just doing something wrong or if this is a deeper issue.
**Thank you!**
