### ISSUE TITLE
Make the "img-retina" mixin more flexible

### ISSUE THREAD

**Issue by toncid** [twbs/bootstrap-sass#701]
Hello,

I suggest you simplify the `img-retina` mixin to produce simpler CSS. Often it is not practical to hardcode image dimensions into (S)CSS code.

This will work fine on 2x Retina screens and will remove the need to hardcode the background image dimensions into code.

``` scss
// ==> make width and height parameters optional
@mixin img-retina($file-1x, $file-2x, $width-1x: false, $height-1x: false) {  
  background-image: url(if($bootstrap-sass-asset-helper, twbs-image-path("#{$file-1x}"), "#{$file-1x}"));

  @media
  only screen and (-webkit-min-device-pixel-ratio: 2),
  only screen and (   min--moz-device-pixel-ratio: 2),
  only screen and (     -o-min-device-pixel-ratio: 2/1),
  only screen and (        min-device-pixel-ratio: 2),
  only screen and (                min-resolution: 192dpi),
  only screen and (                min-resolution: 2dppx) {
    background-image: url(if($bootstrap-sass-asset-helper, twbs-image-path("#{$file-2x}"), "#{$file-2x}"));

    // ==> one way to handle missing parameters
    @if not $width-1x and not $height-1x {
      background-size: 50%;
    } @else {
      // ==> fall back to "auto" if a parameter is missing
      background-size: if($width-1x, $width-1x, "auto") if($height-1x, $height-1x, "auto");
    }
  }
}
```

Thoughts?
