### ISSUE TITLE
make-container() please

### ISSUE THREAD

**Issue by vespakoen** [twbs/bootstrap-sass#739]
This works for me =)

``` scss
@mixin make-container() {
  @include container-fixed();

  @media (min-width: $screen-sm-min) {
    width: $container-sm;
  }
  @media (min-width: $screen-md-min) {
    width: $container-md;
  }
  @media (min-width: $screen-lg-min) {
    width: $container-lg;
  }
}
```
