### ISSUE TITLE
assets_path should = 'assets' in Rails

### ISSUE THREAD

**Issue by chalmagean** [twbs/bootstrap-sass#797]
In Rails you have the option of changing the asset path (for development) and hard-coding the 'assets' folder in the path breaks that.

For me it only seems to fail on custom fonts (in Rails 4.1.5)

`application.rb`

``` ruby
    config.assets.paths << Rails.root.join("app", "assets", "fonts")
    config.assets.precompile << /\.(?:svg|eot|woff|ttf)$/
```

`environments/development.rb`

``` ruby
  config.assets.prefix = "/dev-assets"
  config.serve_static_assets = false¬
  config.assets.compile = false
  config.assets.js_compressor = :uglifier
  config.assets.digest = true
```

``` css
@font-face {
  font-family: 'si';
  src: font-url('socicon.eot');
  src: font-url('socicon.eot?#iefix') format('embedded-opentype'),
       font-url('socicon.woff') format('woff'),
       font-url('socicon.ttf') format('truetype'),
       font-url('socicon.svg#icomoonregular') format('svg');
  font-weight: normal;
  font-style: normal;
}

@media screen and (-webkit-min-device-pixel-ratio:0) {
  @font-face {
    font-family:si;
    src: font-url('socicon.svg') format('svg');
  }
}
```

See how it's looking for `/assets` instead of `/dev-assets`

```
2014/12/11 16:26:10 [error] 69624#0: *9 open() "./public/assets/socicon-0348b245b8a560083c14b1a98cb1ba8a.svg" failed (2: No such file or directory), client: 127.0.0.1, server: _, request: "GET /assets/socicon-0348b245b8a560083c14b1a98cb1ba8a.svg HTTP/1.1", host: "localhost:3001", referrer: "http://localhost:3001/"
```
