### ISSUE TITLE
Large output file after compilation

### ISSUE THREAD

**Issue by robertzajda** [twbs/bootstrap-sass#967]
I just moved from less to sass. After compilation of clean bootstrap I have 153KB output file.
But when added simple code:
```css
input[type=date],
input[type=datetime],
input[type=datetime-local],
input[type=email],
input[type=image],
input[type=month],
input[type=number],
input[type=password],
input[type=search],
input[type=tel],
input[type=text],
input[type=time],
input[type=url],
input[type=week],
textarea,
select {
	@extend .form-control;
	z-index: initial;
}
```
my output file size is 217KB!
What's the problem?
I used:
Bootstrap v3.3.5
```
$ sassc -v
sassc: na
libsass: na
sass2scss: 1.0.3
```
The same code with less compiled OK.

Regards,
Robert
